use_frameworks!

platform :ios, '9.0'

target 'RotationFaceDetection_Example' do
  pod 'RotationFaceDetection', :path => '../'

  target 'RotationFaceDetection_Tests' do
    inherit! :search_paths

    
  end
end
